supershoes_store:
    type: rest
    prefix: /
    resource: SuperShoesBundle\Controller\StoreController
    name_prefix:  supershoes_

supershoes_article:
    type: rest
    prefix: /
    resource: SuperShoesBundle\Controller\ArticleController
    name_prefix:  supershoes_