<?php

namespace SuperShoesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends EntityRepository
{
    public function findAllArticles($store_id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM SuperShoesBundle:Article a WHERE a.store = :store')
            ->setParameter('store', $store_id)
            ->getResult();
    }
}
